### ISSUE TITLE
FitWeibullTAFCTest.m failing

### ISSUE THREAD

**Issue by yarikoptic** [Psychtoolbox-3/Psychtoolbox-3#133]
Finally something which looks like a legit failure ;-) so decided to place it into issue tracker

Testing with octave while building NeuroDebian packages

```
I: Psychtoolbox/PsychTests/FitWeibullTAFCTest.m: 
  D: warning: function /usr/share/octave/packages/statistics-1.1.3/fstat.m shadows a core library function
  D: PTB-WARNING: XRandR extension unsupported. Display infos and configuration functions will be very limited!
  D: warning: unrecognized option: Diagnostics
  D: warning: unrecognized option: LargeScale
  D: error: Invalid call to fminunc.  Correct usage is:
  D: 
  D:  -- Function File:  fminunc (FCN, X0)
  D:  -- Function File:  fminunc (FCN, X0, OPTIONS)
  D:  -- Function File: [X, FVEC, INFO, OUTPUT, GRAD, HESS] = fminunc (FCN,
  D:           ...)
  D:  
  D: error: called from:
  D: error:   /usr/share/octave/3.6.2/m/help/print_usage.m at line 87, column 5
  D: error:   /usr/share/octave/3.6.2/m/optimization/fminunc.m at line 96, column 5
  D: error:   /home/yoh/deb/perspect/psychtoolbox/psychtoolbox-3/Psychtoolbox/Psychometric/FitWeibTAFC.m at line 61, column 5
  D: error:   /home/yoh/deb/perspect/psychtoolbox/psychtoolbox-3/Psychtoolbox/PsychTests/FitWeibullTAFCTest.m at line 19, column 22
```
