### ISSUE TITLE
AlphaMultiplicationTest.m failing: 

### ISSUE THREAD

**Issue by yarikoptic** [Psychtoolbox-3/Psychtoolbox-3#134]
if it says that it is failing -- who am I to say otherwise?  This is while running under Xvfb ...

```
I: Psychtoolbox/PsychTests/AlphaMultiplicationTest.m: 
  D: warning: function /usr/share/octave/packages/statistics-1.1.3/fstat.m shadows a core library function
  D: PTB-WARNING: XRandR extension unsupported. Display infos and configuration functions will be very limited!
  D: warning: function name `AlphaMultipicationTest' does not agree with function file name `/home/yoh/deb/perspect/psychtoolbox/psychtoolbox-3/Psychtoolbox/PsychTests/AlphaMultiplicationTest.m'
  D: Xlib:  extension "XFree86-VidModeExtension" missing on display ":20".
  D: 
  D: 
  D: PTB-INFO: This is Psychtoolbox-3 for GNU/Linux X11, under GNU/Octave-3 64-Bit (Version 3.0.10 - Build date: May 20 2013).
  D: PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
  D: PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
  D: PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.
  D: 
  D: PTB-WARNING: Your graphics driver doesn't allow me to control syncing wrt. vertical retrace!
  D: PTB-WARNING: Please update your display graphics driver as soon as possible to fix this.
  D: PTB-WARNING: Until then, you can manually enable syncing to VBL somehow in a manner that is
  D: PTB-WARNING: dependent on the type of gfx-card and driver. Google is your friend...
  D: PTB-INFO: Intel Corporation - Mobile 4 Series Chipset Integrated Graphics Controller GPU found. Trying to establish low-level access...
  D: PTB-INFO: Failed to map GPU low-level control registers for screenId 0 [Permission denied].
  D: PTB-INFO: Beamposition timestamping and other special functions disabled.
  D: PTB-INFO: You need to run Matlab/Octave with root-privileges, or run the script PsychLinuxConfiguration once for this to work.
  D: PTB-INFO: However, if you are using the free graphics drivers, there isn't any need for this.
  D: PTB-WARNING: At least one test call for OpenML OML_sync_control extension failed! Will disable OpenML and revert to fallback implementation.
  D: Xlib:  extension "XFree86-VidModeExtension" missing on display ":20".
  D: 
  D: 
  D: PTB-INFO: OpenGL-Renderer is VMware, Inc. :: Gallium 0.4 on llvmpipe (LLVM 0x209) :: 2.1 Mesa 8.0.5
  D: PTB-INFO: VBL startline = 768 , VBL Endline = -1
  D: PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
  D: PTB-INFO: Measured monitor refresh interval from VBLsync = 0.000000 ms [inf Hz]. (0 valid samples taken, stddev=0.000000 ms.)
  D: PTB-INFO: Small deviations between reported values are normal and no reason to worry.
  D: PTB-INFO: All display tests and calibrations disabled. Assuming a refresh interval of 60.000000 Hz. Timing will be inaccurate!
  D: PTB-INFO: Support for fast OffscreenWindows enabled.
  D: ans =
  D: 
  D:    16   16    3
  D: 
  D: error: Failed test
  D: error: called from:
  D: error:   /home/yoh/deb/perspect/psychtoolbox/psychtoolbox-3/Psychtoolbox/PsychTests/AlphaMultiplicationTest.m at line 478, column 9
  D: 
  D: 
  D: INFO: PTB's Screen('Flip', 10) command seems to have missed the requested stimulus presentation deadline
  D: INFO: a total of 4 times out of a total of 16 flips during this session.
  D: 
  D: INFO: This number is fairly accurate (and indicative of real timing problems in your own code or your system)
  D: INFO: if you provided requested stimulus onset times with the 'when' argument of Screen('Flip', window [, when]);
  D: INFO: If you called Screen('Flip', window); without the 'when' argument, this count is more of a ''mild'' indicator
  D: INFO: of timing behaviour than a hard reliable measurement. Large numbers may indicate problems and should at least
  D: INFO: deserve your closer attention. Cfe. 'help SyncTrouble', the FAQ section at www.psychtoolbox.org and the
  D: INFO: examples in the PDF presentation in PsychDocumentation/Psychtoolbox3-Slides.pdf for more info and timing tips.
  D: 
  D: 
  D: 
  D: WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 2).
  D: WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
  D: WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
  D: WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.
```
