### ISSUE TITLE
DeinterlacerTest.m: Your OpenGL command glUniform1f() caused the following OpenGL error: invalid operation. Aborted.

### ISSUE THREAD

**Issue by yarikoptic** [Psychtoolbox-3/Psychtoolbox-3#136]
Originally under Xvfb but then tested on real hardware (Intel chipset GM45)

```
I: Psychtoolbox/PsychTests/DeinterlacerTest.m:
  D: warning: function /usr/share/octave/packages/statistics-1.1.3/fstat.m shadows a core library function
  D: PTB-WARNING: XRandR extension unsupported. Display infos and configuration functions will be very limited!
  D: Xlib:  extension "XFree86-VidModeExtension" missing on display ":20".
  D:
  D:
  D: PTB-INFO: This is Psychtoolbox-3 for GNU/Linux X11, under GNU/Octave-3 64-Bit (Version 3.0.10 - Build date: May 20 2013).
  D: PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
  D: PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
  D: PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.
  D:
  D: PTB-WARNING: Your graphics driver doesn't allow me to control syncing wrt. vertical retrace!
  D: PTB-WARNING: Please update your display graphics driver as soon as possible to fix this.
  D: PTB-WARNING: Until then, you can manually enable syncing to VBL somehow in a manner that is
  D: PTB-WARNING: dependent on the type of gfx-card and driver. Google is your friend...
  D: PTB-INFO: Intel Corporation - Mobile 4 Series Chipset Integrated Graphics Controller GPU found. Trying to establish low-level access...
  D: PTB-INFO: Failed to map GPU low-level control registers for screenId 0 [Permission denied].
  D: PTB-INFO: Beamposition timestamping and other special functions disabled.
  D: PTB-INFO: You need to run Matlab/Octave with root-privileges, or run the script PsychLinuxConfiguration once for this to work.
  D: PTB-INFO: However, if you are using the free graphics drivers, there isn't any need for this.
  D: PTB-WARNING: At least one test call for OpenML OML_sync_control extension failed! Will disable OpenML and revert to fallback implementation.
  D: Xlib:  extension "XFree86-VidModeExtension" missing on display ":20".
  D:
  D:
  D: PTB-INFO: OpenGL-Renderer is VMware, Inc. :: Gallium 0.4 on llvmpipe (LLVM 0x209) :: 2.1 Mesa 8.0.5
  D: PTB-INFO: VBL startline = 768 , VBL Endline = -1
  D: PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
  D: PTB-INFO: Measured monitor refresh interval from VBLsync = 0.000000 ms [inf Hz]. (0 valid samples taken, stddev=0.000000 ms.)
  D: PTB-INFO: Small deviations between reported values are normal and no reason to worry.
  D: PTB-INFO: All display tests and calibrations disabled. Assuming a refresh interval of 60.000000 Hz. Timing will be inaccurate!
  D: PTB-INFO: Support for fast OffscreenWindows enabled.
  D: Building a fragment shader:Reading shader from file /home/yoh/deb/perspect/psychtoolbox/psychtoolbox-3/Psychtoolbox/PsychOpenGL/PsychGLSLShaders/EXPDeinterlaceShaderLineDouble.frag.txt ...
  D:
  D:
  D: WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 2).
  D: WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
  D: WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
  D: WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.
  D: moglcore: MOGL-Error: Your OpenGL command glUniform1f() caused the following OpenGL error: invalid operation. Aborted.
  D: error: called from `glUniform1f' in file /home/yoh/deb/perspect/psychtoolbox/psychtoolbox-3/Psychtoolbox/PsychOpenGL/MOGL/wrap/glUniform1f.m near line 15, column 1
```
